@extends('site.master')
@section('content')
    <!-- Calendar Section -->
    <div class="calendar-container">
        <div class="calendar-header">
            <button class="nav-btn" onclick="changeMonth(-1)"><i class="fas fa-chevron-left"></i></button>
            <h2 id="current-month">March 2025</h2>
            <button class="nav-btn" onclick="changeMonth(1)"><i class="fas fa-chevron-right"></i></button>
        </div>

        <div class="weekdays">
            <div>Sun</div>
            <div>Mon</div>
            <div>Tue</div>
            <div>Wed</div>
            <div>Thu</div>
            <div>Fri</div>
            <div>Sat</div>
        </div>

        <div class="days" id="calendar-days">
            <!-- Calendar days will be generated by JavaScript -->
        </div>
    </div>
@endsection
